[2024-10-23T02:30:48.019+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T02:30:48.071+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_etl.transform scheduled__2024-10-20T00:00:00+00:00 [queued]>
[2024-10-23T02:30:48.096+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_etl.transform scheduled__2024-10-20T00:00:00+00:00 [queued]>
[2024-10-23T02:30:48.099+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-23T02:30:48.285+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2024-10-20 00:00:00+00:00
[2024-10-23T02:30:48.305+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-23T02:30:48.313+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2024-10-23T02:30:48.320+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sample_etl', 'transform', 'scheduled__2024-10-20T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/simple_etl.py', '--cfg-path', '/tmp/tmpq1wo1pzq']
[2024-10-23T02:30:48.326+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask transform
[2024-10-23T02:30:48.541+0000] {task_command.py:467} INFO - Running <TaskInstance: sample_etl.transform scheduled__2024-10-20T00:00:00+00:00 [running]> on host 65fa52b3600c
[2024-10-23T02:30:48.821+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-20T00:00:00+00:00'
[2024-10-23T02:30:48.826+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-23T02:30:48.834+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-23T02:30:48.837+0000] {logging_mixin.py:190} INFO - Current task name:transform state:running start_date:2024-10-23 02:30:48.073490+00:00
[2024-10-23T02:30:48.840+0000] {logging_mixin.py:190} INFO - Dag name:sample_etl and current dag run status:running
[2024-10-23T02:30:48.855+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T02:30:48.858+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_etl.py", line 23, in transform
    transformed_data = {**data, 'age_category': 'Adult' if data['age'] > 18 else 'Minor'}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not a mapping
[2024-10-23T02:30:48.893+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-23T02:30:48.895+0000] {logging_mixin.py:190} INFO - Task start:2024-10-23 02:30:48.073490+00:00 end:2024-10-23 02:30:48.893052+00:00 duration:0.819562
[2024-10-23T02:30:48.898+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform> dag:<DAG: sample_etl> dagrun:<DagRun sample_etl @ 2024-10-20 00:00:00+00:00: scheduled__2024-10-20T00:00:00+00:00, state:running, queued_at: 2024-10-23 02:30:35.321665+00:00. externally triggered: False>
[2024-10-23T02:30:48.900+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object is not a mapping
[2024-10-23T02:30:48.901+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_etl, task_id=transform, run_id=scheduled__2024-10-20T00:00:00+00:00, execution_date=20241020T000000, start_date=20241023T023048, end_date=20241023T023048
[2024-10-23T02:30:48.937+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T02:30:48.940+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task transform ('str' object is not a mapping; 146)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_etl.py", line 23, in transform
    transformed_data = {**data, 'age_category': 'Adult' if data['age'] > 18 else 'Minor'}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not a mapping
[2024-10-23T02:30:48.992+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-23T02:30:49.035+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T02:30:49.045+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
