[2024-10-17T18:32:25.266+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T18:32:25.279+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_etl.transform manual__2024-10-17T18:32:21.835580+00:00 [queued]>
[2024-10-17T18:32:25.287+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_etl.transform manual__2024-10-17T18:32:21.835580+00:00 [queued]>
[2024-10-17T18:32:25.288+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T18:32:25.296+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform> on 2024-10-17 18:32:21.835580+00:00
[2024-10-17T18:32:25.302+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T18:32:25.304+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sample_etl', 'transform', 'manual__2024-10-17T18:32:21.835580+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/simple_etl.py', '--cfg-path', '/tmp/tmpwllwfomr']
[2024-10-17T18:32:25.304+0000] {standard_task_runner.py:72} INFO - Started process 160 to run task
[2024-10-17T18:32:25.305+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask transform
[2024-10-17T18:32:25.338+0000] {task_command.py:467} INFO - Running <TaskInstance: sample_etl.transform manual__2024-10-17T18:32:21.835580+00:00 [running]> on host 1a738d4b19e8
[2024-10-17T18:32:25.396+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T18:32:21.835580+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T18:32:21.835580+00:00'
[2024-10-17T18:32:25.397+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-17T18:32:25.398+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-17T18:32:25.398+0000] {logging_mixin.py:190} INFO - Current task name:transform state:running start_date:2024-10-17 18:32:25.280346+00:00
[2024-10-17T18:32:25.399+0000] {logging_mixin.py:190} INFO - Dag name:sample_etl and current dag run status:running
[2024-10-17T18:32:25.399+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T18:32:25.400+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_etl.py", line 23, in transform
    transformed_data = {**data, 'age_category': 'Adult' if data['age'] > 18 else 'Minor'}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not a mapping
[2024-10-17T18:32:25.412+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-17T18:32:25.413+0000] {logging_mixin.py:190} INFO - Task start:2024-10-17 18:32:25.280346+00:00 end:2024-10-17 18:32:25.412400+00:00 duration:0.132054
[2024-10-17T18:32:25.413+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform> dag:<DAG: sample_etl> dagrun:<DagRun sample_etl @ 2024-10-17 18:32:21.835580+00:00: manual__2024-10-17T18:32:21.835580+00:00, state:running, queued_at: 2024-10-17 18:32:21.848054+00:00. externally triggered: True>
[2024-10-17T18:32:25.414+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object is not a mapping
[2024-10-17T18:32:25.414+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_etl, task_id=transform, run_id=manual__2024-10-17T18:32:21.835580+00:00, execution_date=20241017T183221, start_date=20241017T183225, end_date=20241017T183225
[2024-10-17T18:32:25.425+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T18:32:25.425+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task transform ('str' object is not a mapping; 160)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_etl.py", line 23, in transform
    transformed_data = {**data, 'age_category': 'Adult' if data['age'] > 18 else 'Minor'}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not a mapping
[2024-10-17T18:32:25.442+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T18:32:25.458+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T18:32:25.460+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
