[2024-10-23T02:53:34.565+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T02:53:34.596+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_move_dag.move_files_task scheduled__2024-10-22T00:00:00+00:00 [queued]>
[2024-10-23T02:53:34.605+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_move_dag.move_files_task scheduled__2024-10-22T00:00:00+00:00 [queued]>
[2024-10-23T02:53:34.607+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-23T02:53:34.627+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): move_files_task> on 2024-10-22 00:00:00+00:00
[2024-10-23T02:53:34.636+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'file_move_dag', 'move_files_task', 'scheduled__2024-10-22T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dp.py', '--cfg-path', '/tmp/tmptmtfbj4b']
[2024-10-23T02:53:34.638+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask move_files_task
[2024-10-23T02:53:34.636+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-23T02:53:34.645+0000] {standard_task_runner.py:72} INFO - Started process 107 to run task
[2024-10-23T02:53:34.726+0000] {task_command.py:467} INFO - Running <TaskInstance: file_move_dag.move_files_task scheduled__2024-10-22T00:00:00+00:00 [running]> on host c85a6004b767
[2024-10-23T02:53:34.818+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='file_move_dag' AIRFLOW_CTX_TASK_ID='move_files_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-22T00:00:00+00:00'
[2024-10-23T02:53:34.827+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-23T02:53:34.828+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-23T02:53:34.829+0000] {logging_mixin.py:190} INFO - Current task name:move_files_task state:running start_date:2024-10-23 02:53:34.597169+00:00
[2024-10-23T02:53:34.830+0000] {logging_mixin.py:190} INFO - Dag name:file_move_dag and current dag run status:running
[2024-10-23T02:53:34.830+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T02:53:34.832+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dp.py", line 16, in move_files
    for filename in os.listdir(source_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ganga/Projects/DE/airflow-docker/source'
[2024-10-23T02:53:34.847+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-23T02:53:34.848+0000] {logging_mixin.py:190} INFO - Task start:2024-10-23 02:53:34.597169+00:00 end:2024-10-23 02:53:34.847158+00:00 duration:0.249989
[2024-10-23T02:53:34.849+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): move_files_task> dag:<DAG: file_move_dag> dagrun:<DagRun file_move_dag @ 2024-10-22 00:00:00+00:00: scheduled__2024-10-22T00:00:00+00:00, state:running, queued_at: 2024-10-23 02:53:30.042692+00:00. externally triggered: False>
[2024-10-23T02:53:34.850+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:/Users/ganga/Projects/DE/***-docker/source'
[2024-10-23T02:53:34.850+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=file_move_dag, task_id=move_files_task, run_id=scheduled__2024-10-22T00:00:00+00:00, execution_date=20241022T000000, start_date=20241023T025334, end_date=20241023T025334
[2024-10-23T02:53:34.872+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T02:53:34.873+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task move_files_task ([Errno 2] No such file or directory: 'C:/Users/ganga/Projects/DE/airflow-docker/source'; 107)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dp.py", line 16, in move_files
    for filename in os.listdir(source_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ganga/Projects/DE/airflow-docker/source'
[2024-10-23T02:53:34.981+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-23T02:53:35.013+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T02:53:35.021+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
